
version: '3.9'
services:
 web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes: [".:/app"]
  ports: ["8000:8000"]
  depends_on: [db,redis]
  environment:
   POSTGRES_HOST: db
   POSTGRES_PORT: 5432

 db:
  image: postgres:15
  environment:
   POSTGRES_DB: postgres
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres

 redis:
  image: redis:7

 worker:
  build: .
  command: celery -A config worker -l info
  depends_on: [web,redis]
  environment:
   POSTGRES_HOST: db
   POSTGRES_PORT: 5432
